import type {State} from "../lib/client";
import {Empty,Icon,Panel} from "./ui";
import {Stat} from "./Operations";
export function Configuration({state}:{state:State}){
 const config=state.configuration;
 const lua=["set_queue {", "  capacity = "+config.queue_capacity+",", "  timeout_ms = "+config.queue_timeout_ms,"}","","set_runtime {","  threads = "+config.threads+",","  work_stealing = "+config.work_stealing+",","  upstream_keepalive_capacity = "+config.upstream_keepalive_capacity+",","  write_buffer_bytes = "+config.write_buffer_bytes,"}","","set_persistence {",'  admission = "'+state.policies.persistence_admission+'",','  synchronous = "'+state.policies.persistence_synchronous+'"',"}","","set_model {",'  mode = "'+state.policies.model+'",',"  scan_bytes = "+config.scan_bytes+",",'  on_overload = "'+config.on_overload+'"',"}"].join("\n");
 return <><div className="callout info"><Icon name="settings"/><div><strong>One configuration. Explicit control.</strong><p>This is the active configuration snapshot. Edit your Lua file, validate with <code>--check</code>, then reload. Worker and storage resource changes require a restart.</p></div></div>
 <div className="configuration-grid"><Panel title="Effective runtime" description={"Snapshot "+state.config_version.slice(0,8)}>
 <Stat label="Waiting capacity" value={config.queue_capacity||"Disabled"}/><Stat label="Total wait budget" value={config.queue_timeout_ms+" ms"}/><Stat label="Proxy workers" value={config.threads}/><Stat label="Scheduler" value={config.work_stealing?"Work stealing":"Per-thread runtime"}/><Stat label="Accept tasks / descriptor" value={config.accept_tasks}/><Stat label="Idle upstream pool" value={config.upstream_keepalive_capacity}/><Stat label="Keepalive" value={config.keepalive_seconds+" seconds"}/><Stat label="Concurrency limit" value={state.policies.max_in_flight}/><Stat label="Rate limit / 10 seconds" value={state.policies.rate_limit_10s||"Unlimited"}/><Stat label="Schema / features" value={config.feature_version+" / "+config.feature_count}/></Panel>
 <Panel title="Lua policy preview" description="Selected effective values; not a complete replacement file." className="code-panel"><div className="code-file"><span/><span/><span/><b>Aegisx.lua</b></div><pre><code>{lua}</code></pre></Panel></div>
 <Panel title="Routing policies" description={config.route_count+" explicit routes. The default upstream fallback is configured separately."}>
 <div className="table-scroll" tabIndex={0}><table><thead><tr><th>Route</th><th>Host / path</th><th>Upstream</th><th>Analysis</th><th>Capture</th><th>Rate / 10s</th></tr></thead><tbody>{config.routes.map(route=><tr key={route.name}><td><strong>{route.name}</strong></td><td><div className="mono">{route.path}</div><small className="muted">{route.host??"Any host"} · {route.exact?"Exact":"Prefix"} · {route.methods.join(", ")||"All methods"}</small></td><td>{route.deny?<span className="badge danger">Deny</span>:route.upstream}</td><td><span className="badge violet">{route.model}</span></td><td>{route.capture?"On":"Off"}</td><td>{route.rate_limit_10s||"Unlimited"}</td></tr>)}</tbody></table>{!config.routes.length&&<Empty icon="settings" title="Using the default upstream">Add explicit routes in Lua when endpoints need their own policy.</Empty>}</div></Panel></>;
}
